// <auto-generated />
using Cardapio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cardapio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221120235032_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Cardapio.Models.Bebida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Bebidas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            ImageUrl = "https://www.mundoboaforma.com.br/wp-content/uploads/2017/09/suco-de-maca-1-620x330.jpg",
                            Name = "Suco de maçã",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            ImageUrl = "https://th.bing.com/th/id/OIP.W6ZV25EGvJ3dx1lelLVAHQHaFD?pid=ImgDet&rs=1",
                            Name = "Suco de laranja com morango",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            ImageUrl = "https://www.tecnonutrireceitas.com.br/central/Content/handlers/Receita.ashx?id=82727&tipo=r&default=s",
                            Name = "Suco de limão de siciliano com hortelã",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            ImageUrl = "https://th.bing.com/th/id/OIP.2RlEdsGDOUkUH6bTTVYGywHaEd?pid=ImgDet&rs=1",
                            Name = "Suco de maracujá com creme de leite",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            ImageUrl = "https://www.dessertnowdinnerlater.com/wp-content/uploads/2019/04/Strawberry-Agua-Fresca-3.jpg",
                            Name = " Pink lemonade",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            ImageUrl = "https://boaforma.abril.com.br/wp-content/uploads/sites/2/2017/11/suco-verde.jpg",
                            Name = "Suco verde",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            ImageUrl = "https://www.dicasdetreino.com.br/wp-content/uploads/2019/01/Receitas-de-Suco-Detox-para-Limpar-o-Organismo.jpg",
                            Name = "Suco detox",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            ImageUrl = "https://th.bing.com/th/id/OIP.d4KfVU9uxtnfnyjWMrzhywHaFf?pid=ImgDet&w=1200&h=889&rs=1",
                            Name = " Suco digestivo",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            ImageUrl = "https://th.bing.com/th/id/OIP.zUlgeMS7vrs1O3WRBfqQoQHaEe?pid=ImgDet&w=1800&h=1087&rs=1",
                            Name = "Suco frisante de lichia e framboesa",
                            Price = 7.5
                        });
                });

            modelBuilder.Entity("Cardapio.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sanduiche"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bebida"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salada"
                        });
                });

            modelBuilder.Entity("Cardapio.Models.Salada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Saladas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 3,
                            Description = " milho, ervilha, pepino, frango, alface, cenoura, tomate, ovo e abacaxi",
                            ImageUrl = "https://img.itdg.com.br/images/recipes/000/197/343/299262/299262_original.jpg",
                            Name = "Salada americana",
                            Price = 11.5
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 3,
                            Description = "alface, pepino, alface, rabanete e pão sírio.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.p1rSlUHGreAK-lqo-sFmXwHaJQ?pid=ImgDet&rs=1",
                            Name = "Salada fatoush",
                            Price = 11.5
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Description = " batata, a ervilha, a maionese e a cenoura.",
                            ImageUrl = "https://th.bing.com/th/id/R.6eb407b09be8c0fce23592030dae609d?rik=iQbyd5l%2fS0XIZA&pid=ImgRaw&r=0",
                            Name = "Salada russa",
                            Price = 11.5
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Description = "leva maçã, nozes e um incrível milho de iogurte.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.7MwHLJKBOg9N2MNI0E47CwHaFP?pid=ImgDet&w=3000&h=2122&rs=1",
                            Name = "Salada Waldorf",
                            Price = 11.5
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Description = "alface, agrião, frango assado ou grelhado, bacon, ovo cozido, abacate, queijo e cebolinha.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.2_K6rYsvrBOkQpBvevy4XgHaHa?pid=ImgDet&rs=1",
                            Name = "Salada Cobb",
                            Price = 11.5
                        });
                });

            modelBuilder.Entity("Cardapio.Models.Sanduiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Sanduiches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Description = "pão de forma integral - pasta de ricota - alface - tomate -orégano - salsinha.",
                            ImageUrl = "https://i.pinimg.com/originals/dc/47/54/dc475498f5c9447b7835a4f14d091461.jpg",
                            Name = "sanduíche natural com pasta de ricota",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Description = "pão de forma integral - pasta de cottage - abobrinha - alface - orégano - salsinha.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.gPV-cLEJjFP6GxpcocFvdgHaEz?pid=ImgDet&w=870&h=565&rs=1",
                            Name = "sanduíche natural com abobrinha",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Description = "pão de forma integral - queijo minas -peito de peru - alface - tomate - orégano - salsinha. ",
                            ImageUrl = "https://th.bing.com/th/id/OIP.5E5S3QnsSIeGBr-Xg0RSAQHaE8?pid=ImgDet&w=700&h=467&rs=1",
                            Name = "sanduíche natural com peito de peru ",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Description = "pão de forma integral - atum escorrido light - alface - tomate - orégano - salsinha.",
                            ImageUrl = "https://d37k6lxrz24y4c.cloudfront.net/v2/pt-br/e9dc924f238fa6cc29465942875fe8f0/9f0e0e13-00d5-4b58-a209-e01527581ea2-900.jpg",
                            Name = "sanduíche natural com atum",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Description = "pão de forma integral - cenoura ralada - ovo cozido - alface - orégano a gosto - salsinha.",
                            ImageUrl = "https://1.bp.blogspot.com/-KbFCmjqVtZM/WvmVHFZiMqI/AAAAAAAAXhw/PF_rF5C8-8g-tjPOVkqkBIltu3KJQlK1gCLcBGAs/s1600/Aprenda-7-receitas-de-sandu%25C3%25ADches-naturais-f%25C3%25A1ceis-e-saborosos-5.jpg",
                            Name = "sanduíche natural com cenoura e ovo",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            Description = "pão de forma integral - patê de girassol - alface - tomate.",
                            ImageUrl = "https://i.pinimg.com/originals/aa/a6/c5/aaa6c5dc4d50d231ce78f9e591eb6867.jpg",
                            Name = "sanduíche natural com patê de girassol",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Description = "pão de forma integral - berinjela - alface - tomate - farinha de linhaça - orégano.",
                            ImageUrl = "https://i.pinimg.com/originals/57/17/ac/5717ac47ff81555e1dd51fb225b1d62e.jpg",
                            Name = "sanduíche natural com berinjela ",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 1,
                            Description = "pão de forma integral - queijo cottage - espinafre cozido - tomate - orégano - salsinha.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.PZ3rsF75tOxYo0a8YAVVLgHaE7?pid=ImgDet&rs=1",
                            Name = "sanduíche natural com espinafre",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 1,
                            Description = "pão de forma integral - guacamole - alface - tomate - orégano - salsinha.",
                            ImageUrl = "https://i.pinimg.com/originals/85/ec/f1/85ecf102f9f31dca543a1ad9baf236e6.jpg",
                            Name = " sanduíche natural com guacamole",
                            Price = 9.5
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 1,
                            Description = "pão de forma integral - queijo minas - peito de peru - picles - abacaxi picado - alface.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.JIzaWWXB4QG7wq9NhhNaYQHaFL?pid=ImgDet&rs=1",
                            Name = "sanduíche natural com abacaxi",
                            Price = 9.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
