// <auto-generated />
using ListaAnime.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListaAnime.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("ListaAnime.Models.Autor", b =>
                {
                    b.Property<long>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("ListaAnime.Models.Genero", b =>
                {
                    b.Property<long>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeGenero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("ListaAnime.Models.Manga", b =>
                {
                    b.Property<long>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AutorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeManga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MangaId");

                    b.HasIndex("AutorId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("ListaAnime.Models.Manga", b =>
                {
                    b.HasOne("ListaAnime.Models.Autor", "Autor")
                        .WithMany("Mangas")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListaAnime.Models.Genero", "Genero")
                        .WithMany("Mangas")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("ListaAnime.Models.Autor", b =>
                {
                    b.Navigation("Mangas");
                });

            modelBuilder.Entity("ListaAnime.Models.Genero", b =>
                {
                    b.Navigation("Mangas");
                });
#pragma warning restore 612, 618
        }
    }
}
